export const ADD_TO_SLOT = "ADD_TO_SLOT";
export const UPDATE_SLOT_QUANTITY = "UPDATE_SLOT_QUANTITY";
export const REMOVE_FROM_SLOT = "REMOVE_FROM_SLOT";
export const UPDATE_DISHES = "UPDATE_DISHES";
export const UPDATE_GUESTS = "UPDATE_GUESTS";
export const UPDATE_CURRENT_EVENT = "UPDATE_CURRENT_EVENT";